spring:
  datasource:
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/logindb
     username: postgres
     password:

  spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect


