/**
 * User entity class
 * Represents user information
 * @author Michelle
 * @version 1
 */
package com.calendar.login.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import lombok.Data;
import jakarta.persistence.Table;
import jakarta.persistence.GenerationType;

@Entity
@Data
@Table
//(name= "user_table")

public class User {

   @Id
   @GeneratedValue(strategy = GenerationType.IDENTITY) // id field is autogenerated
   private long id; //to identify each row in db table

   @Column(unique=true, nullable=false) //every email must be unique
   private String email;
   @Column(nullable=false)
   private String password;

}
